version: "3.2"
services:
  backend:
    build: C:/Users/f_cec/Desenvolvimento/Estudos/Cursos_Udemy/ecommerce_dwr/backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/f_cec/Desenvolvimento/Estudos/Cursos_Udemy/ecommerce_dwr/backend:/var/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - db-net
  frontend:
    build: C:/Users/f_cec/Desenvolvimento/Estudos/Cursos_Udemy/ecommerce_dwr/frontend
    restart: unless-stopped
    # environment:
    #   - WDS_SOCKET_HOST=127.0.0.1 
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true 
    ports:
      - "3000:3000"
    volumes:
      - C:/Users/f_cec/Desenvolvimento/Estudos/Cursos_Udemy/ecommerce_dwr/frontend:/var/frontend
      - /var/frontend/node_modules
      # - nodemodules:/var/frontend/node_modules
    command: bash -c "npm start"
    depends_on:
      - "backend"
    networks:
      - db-net
# volumes:
#   nodemodules: {}
networks:
  db-net:
    driver: bridge